### ISSUE TITLE
Why does #Resources have to be same as #Scopes?

### ISSUE THREAD

**Issue by gerrylowe** [cleancodelabs/IdentityServer4.Contrib.AspNetCore.Testing#5]
AbstractIdentityServerHostBuilder features this validation check:
`protected void Validate()
        {
            if (this.internalApiResources.Any() && this.internalApiResources.Count != this.internalApiScopes.Count)
                throw new InvalidOperationException(
                    "IdentityServer4 version 4 requires API scopes for each API resource!");
        }`
Is it really invalid to have a count mismatch e.g. one Resource with many Scopes?  Apologies if I have a fundamental misunderstanding!  But my actual Identity Server instance uses such a configuration, without error - so I'm surprised that I can't use the same configuration in testing.

**Comment by alsami** [comment]
I am not a hundred percent sure anymore why I have added this requirement but AFAIR, the version 4 had some breaking changes and one of them required that each api resources also needed at least the same api scope.

It might be that the check is incorrect and should just validate that the api scope is present for the resource or vise versa.

Would you mind sending a PR? I'd happily accept it and cut a release.

**Comment by gerrylowe** [comment]
OK, I'll get on it.  I'm thinking that any such consistency check should be lightweight - better to permit invalid configs than forbid valid ones (as at present).  So perhaps just check that each of the scopes for each ApiResource have been specified as an ApiScope.

**Comment by alsami** [comment]
Yeah that makes perfectly sense. There should be tests covering that it still works.

**Comment by gerrylowe** [comment]
PR submitted.  The new validation logic didn't break any tests, I think because no test was setting the Scopes property of any ApiResource.  So I added a test containing an ApiResource with Scopes property set (as well as some matching/mismatching ApiScopes).  I'm still not 100% convinced this is correct/necessary, compared to e.g. just dropping the existing validation altogether!

**Comment by alsami** [comment]
`4.2.0` has been released. Thanks for sending the PR!
